#### **Welcome to Assignment 0 on Deep Learning for Computer Vision.**
In this assignment you will get a chance to understand and work on some of the commonly used functionalities of several Machine Learnign and Data Analysis libraries

#### **Instructions**
1. Use Python 3.x to run this notebook
2. Write your code only in between the lines 'YOUR CODE STARTS HERE' and 'YOUR CODE ENDS HERE'.
3. Look up the documentation for each of the Python and Numpy function used.
4. This Assignment is just to make you understand several commonly used library functions.
5. This assignment is **NOT** evaluated

In [1]:
# DO NOT CHANGE THIS CODE
import numpy as np
np.random.seed(0)

#### Python Basics


In [2]:
### Implement recursive fibonacci in the function below
def recursive_fibonacci(n):
  ## YOUR CODE STARTS HERE
    if(n <= 1):
        return n;
    return recursive_fibonacci(n - 1) + recursive_fibonacci(n -2);
  ## YOUR CODE ENDS HERE

In [3]:
### Test your code using the function call below.
recursive_fibonacci(3)

2

#### Lambda function

In [4]:
def sigmoid(x):
  sigmoid = 1 / (1 + np.exp(-x))
  return sigmoid

## Implement the above sigmoid function using python lambda functions
## YOUR CODE STARTS HERE
sigmoid_lambda = lambda x: 1 / (1 + np.exp(-x))
## YOUR CODE ENDS HERE

In [5]:
## Check you implementation by running this cell (should return True)
sigmoid(1) == sigmoid_lambda(1)

True

#### List Comprehension

In [6]:
div_by_four = []
for number in range(200):
    if number%4 == 0:
        div_by_four.append(number)
        
## Implement the above function using list comprehensions
## YOUR CODE STARTS HERE

# new_list = [expression for item in iterable if condition == True]
div_by_four_lc = [x for x in range(200) if x%4 == 0]
## YOUR CODE ENDS HERE

In [7]:
## Check you implementation by running this cell (should return True)
div_by_four == div_by_four_lc

True

#### Python map keyword
Using the lambda functions and python's map keyword apply sigmoid on a list of numbers from 0 to 99. Store the output in a list and print it. 

**Observe what happens to the value of sigmoid as the value of x increases. Do you see any trend?**

In [9]:
## YOUR CODE STARTS HERE
out = list(map(lambda x: 1/(1 + np.exp(-x)), range(100)))
print(out)
## YOUR CODE ENDS HERE

[0.5, 0.7310585786300049, 0.8807970779778823, 0.9525741268224334, 0.9820137900379085, 0.9933071490757153, 0.9975273768433653, 0.9990889488055994, 0.9996646498695336, 0.9998766054240137, 0.9999546021312976, 0.999983298578152, 0.9999938558253978, 0.999997739675702, 0.9999991684719722, 0.999999694097773, 0.9999998874648379, 0.9999999586006244, 0.9999999847700205, 0.9999999943972036, 0.9999999979388463, 0.9999999992417439, 0.9999999997210531, 0.9999999998973812, 0.9999999999622486, 0.999999999986112, 0.999999999994891, 0.9999999999981204, 0.9999999999993086, 0.9999999999997455, 0.9999999999999065, 0.9999999999999656, 0.9999999999999873, 0.9999999999999953, 0.9999999999999982, 0.9999999999999993, 0.9999999999999998, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,

# Numpy Basics:


#### Creating a numpy array with particular value


In [16]:
# Create a numpy array with size 2*2 with all elements as 8.

# YOUR CODE STARTS HERE
arr = np.full((2, 2), 8)
# arr = np.ones((2, 2)) * 8;
print(arr)
# YOUR CODE ENDS HERE

[[8 8]
 [8 8]]


#### Basic Numpy operations:

In [17]:
#Create a numpy array of size 3*3 with random values 

#YOUR CODE STARTS HERE
rand_arr = np.random.randn(3, 3)
print(rand_arr)
#YOUR CODE ENDS HERE



[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]]


In [19]:
#Find the sum of all the elements, mean, maximum and minimum value of the numpy array defined above

#YOUR CODE STARTS HERE
arr_sum = np.sum(rand_arr)
arr_mean = np.mean(rand_arr)
arr_max = np.max(rand_arr)
arr_min = np.min(rand_arr)

print(arr_sum)
print(arr_mean)
print(arr_max)
print(arr_min)
#YOUR CODE ENDS HERE

6.969633205349975
0.7744036894833306
2.240893199201458
-0.977277879876411


#### Reshaping and Indexing of Numpy Array:

In [24]:
#create a 1D numpy array of shape 35 with values 1,2,3..,35

#YOUR CODE STARTS HERE
y = np.arange(1, 36, 1)
print(y)
#YOUR CODE ENDS HERE

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35]


In [29]:
# Reshape it as 2D array of shape (5,7)

#YOUR CODE STARTS HERE
y = y.reshape(5, 7)
#YOUR CODE ENDS HERE
print(y.shape)
print(y)

(5, 7)
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]]


In [38]:
# Extract all the elements from 2nd and 3rd row

#YOUR CODE STARTS HERE
y_row = y[1:3,:]
print(y_row)
#YOUR CODE ENDS HERE

[[ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


In [44]:
# Extract all the elements from 3rd and 5th and 7th column

#YOUR CODE STARTS HERE
y_column = y[:,2:7:2]
print(y_column)
#YOUR CODE ENDS HERE

[[ 3  5  7]
 [10 12 14]
 [17 19 21]
 [24 26 28]
 [31 33 35]]


#### Horizontal and vertical stacking of numpy array

In [48]:
## horizontal and vertical stacking of 1D arrays 
a = np.array([4.,2.])
b = np.array([3.,8.])

#YOUR CODE STARTS HERE
# Horizontal stacking
h_stack = np.hstack((a, b))
print(h_stack)

# Vertical Stacking
v_stack = np.vstack((a, b))
print(v_stack)
#YOUR CODE ENDS HERE

[4. 2. 3. 8.]
[[4. 2.]
 [3. 8.]]


#### `argmin` and `argmax` in numpy array

In [54]:
# Define an array
arr = np.array([[5,12,51,25],
                [25,29,2,27]])

# YOUR CODE STARTS HERE
#Find the position of maximum and minimum value of above array
max_idx = np.argmax(arr)
min_idx = np.argmin(arr)
print (max_idx,min_idx)

#Find the indices of maximum and minimum value along each of its columns.
max_col = np.argmax(arr, axis=0)
min_col = np.argmin(arr, axis=0)
print (max_col,min_col)

#Find the indices of maximum and minimum value along each of the its rows.
max_row = np.argmax(arr, axis=1)
min_row = np.argmin(arr, axis=1)
print (max_row,min_row)
#YOUR CODE ENDS HERE

2 6
[1 1 0 1] [0 0 1 0]
[2 1] [0 2]
